const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const TOKEN_KEY="sheen-finance-token",LEGACY_KEY="sheen-finance-v2";
let token=localStorage.getItem(TOKEN_KEY)||sessionStorage.getItem(TOKEN_KEY)||"",rows=[],members=[],periods={},editing=null,editingMember=null,currentUser=null,currentRole="guest";
const labels={income:"دریافتی",expense:"هزینه",withdrawal:"برداشت"},colors={income:"var(--green)",expense:"var(--red)",withdrawal:"var(--gold)"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const toman=n=>new Intl.NumberFormat("fa-IR").format(Number(n)||0)+" تومان";
const normalizeDigits=v=>String(v).replace(/[۰-۹]/g,d=>"۰۱۲۳۴۵۶۷۸۹".indexOf(d)).replace(/[٠-٩]/g,d=>"٠١٢٣٤٥٦٧٨٩".indexOf(d));
const parseMoney=v=>Number(normalizeDigits(v).replace(/[^0-9]/g,""))||0;
const formatMoneyInput=v=>{const n=parseMoney(v);return n?new Intl.NumberFormat("fa-IR").format(n):""};
function periodKey(v){const p=new Intl.DateTimeFormat("en-u-ca-persian",{year:"numeric",month:"2-digit",timeZone:"Asia/Tehran"}).formatToParts(new Date(v));return p.find(x=>x.type==="year").value+"-"+p.find(x=>x.type==="month").value}
const currentPeriod=periodKey(new Date());
function periodLabel(p){const [y,m]=p.split("-").map(Number),n=["فروردین","اردیبهشت","خرداد","تیر","مرداد","شهریور","مهر","آبان","آذر","دی","بهمن","اسفند"];return(n[m-1]||m)+" "+new Intl.NumberFormat("fa-IR",{useGrouping:false}).format(y)}
function fmtDate(v){return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Tehran"}).format(new Date(v))}
function localDT(v=new Date()){const d=new Date(v),z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}
function canEdit(){return currentRole==="owner"||currentRole==="admin"}
function canEditRow(r){return currentRole==="owner"||(currentRole==="admin"&&r.period===currentPeriod&&!periods[r.period]?.closed)}
function stats(list=rows){let income=0,expense=0,withdrawal=0;for(const r of list){if(r.kind==="income")income+=r.amount;if(r.kind==="expense")expense+=r.amount;if(r.kind==="withdrawal")withdrawal+=r.amount}const profit=income-expense;return{income,expense,withdrawal,profit,cash:profit-withdrawal}}
function toast(v){$("#toast").textContent=v;$("#toast").style.display="block";setTimeout(()=>$("#toast").style.display="none",2500)}
async function api(url,opt={}){const headers={"Content-Type":"application/json",...(opt.headers||{})};if(token)headers.Authorization="Bearer "+token;const r=await fetch("/api"+url,{...opt,headers});let data={};try{data=await r.json()}catch{}if(!r.ok){if(r.status===401&&url!=="/auth/login")logout();throw new Error(data.error||"خطا در ارتباط با سرور")}return data}
function rowHTML(r){return `<div class="row">${canEditRow(r)?`<button class="edit" data-edit="${r.id}">ویرایش</button>`:"<span></span>"}<div><div class="row-title">${esc(r.desc)}</div><div class="meta">${fmtDate(r.date)} · ${esc(r.actorName||r.actorEmail||"—")}</div></div><div><div class="amount" style="color:${colors[r.kind]}">${toman(r.amount)}</div><div class="kind">${labels[r.kind]}</div></div></div>`}
function filteredRows(){const q=normalizeDigits($("#searchTx")?.value||"").toLowerCase(),month=$("#monthFilter")?.value||"all",kind=$("#kindFilter")?.value||"all";return rows.filter(r=>(month==="all"||r.period===month)&&(kind==="all"||r.kind===kind)&&(!q||normalizeDigits(r.desc).toLowerCase().includes(q)||String(r.amount).includes(q.replace(/\D/g,""))))}
function render(){
 const s=stats(),sorted=[...rows].sort((a,b)=>new Date(b.date)-new Date(a.date));
 $("#metrics").innerHTML=[["کل درآمد",s.income,"var(--green)"],["کل هزینه",s.expense,"var(--red)"],["سود خالص",s.profit,"var(--gold)"],["موجودی صندوق",s.cash,"var(--blue)"]].map(x=>`<div class="metric"><div class="dot" style="background:${x[2]}"></div><div class="label">${x[0]}</div><div class="value">${toman(x[1])}</div></div>`).join("");
 $("#shares").innerHTML=[[40,"سهم شما",s.profit*.4],[60,"سهم شریک",s.profit*.6]].map(x=>`<div class="share"><div class="between"><strong>${x[1]} <small class="label">${x[0]}٪</small></strong><b>${toman(x[2])}</b></div><div class="bar"><div class="fill" style="width:${x[0]}%"></div></div></div>`).join("");
 $("#recent").innerHTML=sorted.slice(0,3).map(rowHTML).join("")||'<div class="empty">هنوز تراکنشی ثبت نشده</div>';
 renderTransactions();renderMembers();
 $("#reportRows").innerHTML=[["مجموع دریافتی",s.income],["مجموع هزینه",s.expense],["مجموع برداشت",s.withdrawal],["سود خالص",s.profit],["سهم شما (۴۰٪)",s.profit*.4],["سهم شریک (۶۰٪)",s.profit*.6]].map(x=>`<div class="report-row"><span>${x[0]}</span><strong>${toman(x[1])}</strong></div>`).join("");
 $("#add").style.display=canEdit()?"":"none";$$(".quick").forEach(b=>b.style.display=canEdit()?"":"none");bindEdit();
}
function renderTransactions(){const all=[...new Set(rows.map(r=>r.period).filter(Boolean))].sort().reverse(),sel=$("#monthFilter"),old=sel.value;sel.innerHTML='<option value="all">همه ماه‌ها</option>'+all.map(p=>`<option value="${p}">${periodLabel(p)}${p!==currentPeriod?" (بسته)":""}</option>`).join("");if([...sel.options].some(o=>o.value===old))sel.value=old;const shown=filteredRows().sort((a,b)=>new Date(b.date)-new Date(a.date));$("#allRows").innerHTML=shown.map(rowHTML).join("")||'<div class="empty">تراکنشی پیدا نشد</div>';const p=sel.value;$("#periodNote").innerHTML=p!=="all"&&p!==currentPeriod?`<div class="period-note">ماه ${periodLabel(p)} بسته شده است. ${currentRole==="owner"?"شما به‌عنوان مالک دسترسی کامل دارید.":"اطلاعات این ماه فقط قابل مشاهده است."}</div>`:"";bindEdit()}
function bindEdit(){$$("[data-edit]").forEach(b=>b.onclick=()=>openModal(rows.find(r=>r.id===b.dataset.edit)))}
function renderMembers(){const owner=currentRole==="owner";$("#addMember").style.display=owner?"":"none";if(!owner){$("#memberRows").innerHTML='<div class="empty">مدیریت اعضا فقط در اختیار مالک است.<br><span class="role-badge">سطح شما: '+(currentRole==="admin"?"مدیر":"فقط مشاهده")+"</span></div>";return}$("#memberRows").innerHTML=members.map(m=>`<div class="member-row"><div><div class="row-title">${esc(m.name)}</div><div class="meta" dir="ltr">${esc(m.email)}</div><span class="role-badge">${m.role==="admin"?"مدیر":"فقط مشاهده"}</span></div><div class="member-actions"><button class="edit" data-member-edit="${m.id}">ویرایش</button><button class="danger" data-member-delete="${m.id}">حذف</button></div></div>`).join("")||'<div class="empty">هنوز عضوی اضافه نشده</div>';$$("[data-member-edit]").forEach(b=>b.onclick=()=>openMember(members.find(m=>m.id===b.dataset.memberEdit)));$$("[data-member-delete]").forEach(b=>b.onclick=async()=>{if(confirm("دسترسی این عضو حذف شود؟"))try{await api("/members/"+b.dataset.memberDelete,{method:"DELETE"});await loadAll();toast("دسترسی حذف شد")}catch(e){toast(e.message)}})}
function openModal(r=null,kind="income"){if(!canEdit()||r&&!canEditRow(r))return;editing=r?.id||null;$("#modalTitle").textContent=r?"ویرایش تراکنش":"ثبت تراکنش";$("#kind").value=r?.kind||kind;$("#amount").value=r?.amount?formatMoneyInput(r.amount):"";$("#desc").value=r?.desc||"";$("#date").value=r?.date?localDT(r.date):localDT();$("#modal").showModal()}
function openMember(m=null){if(currentRole!=="owner")return;editingMember=m?.id||null;$("#memberModalTitle").textContent=m?"ویرایش عضو":"افزودن عضو";$("#memberName").value=m?.name||"";$("#memberEmail").value=m?.email||"";$("#memberEmail").disabled=!!m;$("#memberPassword").value="";$("#memberRole").value=m?.role||"viewer";$("#memberModal").showModal()}
async function saveTransaction(){const amount=parseMoney($("#amount").value),desc=$("#desc").value.trim(),date=$("#date").value,kind=$("#kind").value;if(!amount||!desc||!date)return toast("مبلغ، شرح و تاریخ را کامل کن");try{await api("/transactions"+(editing?"/"+editing:""),{method:editing?"PUT":"POST",body:JSON.stringify({amount,desc,kind,date:new Date(date).toISOString()})});$("#modal").close();await loadAll();toast("ذخیره و همگام شد")}catch(e){toast(e.message)}}
async function saveMember(){const name=$("#memberName").value.trim(),email=$("#memberEmail").value.trim().toLowerCase(),role=$("#memberRole").value,password=$("#memberPassword").value;if(!name||(!editingMember&&!/^\S+@\S+\.\S+$/.test(email)))return toast("نام و ایمیل معتبر وارد کن");if(!editingMember&&password.length<8)return toast("رمز باید حداقل ۸ حرف باشد");try{await api("/members"+(editingMember?"/"+editingMember:""),{method:editingMember?"PUT":"POST",body:JSON.stringify({name,email,role,password})});$("#memberModal").close();await loadAll();toast("دسترسی عضو ذخیره شد")}catch(e){toast(e.message)}}
async function importLocal(){let local=[];try{local=JSON.parse(localStorage.getItem(LEGACY_KEY)||"[]")}catch{}if(currentRole!=="owner"||!Array.isArray(local)||!local.length||rows.length)return;try{const r=await api("/import",{method:"POST",body:JSON.stringify(local)});if(r.count){localStorage.removeItem(LEGACY_KEY);toast(r.count+" تراکنش قبلی منتقل شد");await loadAll()}}catch{}}
async function loadAll(){rows=await api("/transactions");periods=await api("/periods");if(currentRole==="owner")members=await api("/members");render()}
function showGate(title,text){$("#authTitle").textContent=title;$("#authText").textContent=text;$("#authGate").classList.remove("hidden")}
function hideGate(){$("#authGate").classList.add("hidden")}
async function enter(user){currentUser=user;currentRole=user.role;hideGate();$("#logout").style.display="inline-block";$("#userbar").innerHTML=`<span>${esc(user.name||user.email)}</span><span class="role-badge">${currentRole==="owner"?"مالک":currentRole==="admin"?"مدیر":"مشاهده‌گر"}</span>`;await loadAll();await importLocal()}
function logout(){token="";currentUser=null;currentRole="guest";localStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TOKEN_KEY);rows=[];members=[];$("#logout").style.display="none";$("#userbar").innerHTML="";showGate("ورود امن","برای ورود، ایمیل و رمز عبور خود را وارد کنید.")}
$("#loginBtn").onclick=async()=>{const email=$("#loginEmail").value.trim(),password=$("#loginPassword").value,remember=$("#rememberMe").checked;$("#loginBtn").disabled=true;try{const r=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});token=r.token;localStorage.removeItem(TOKEN_KEY);sessionStorage.removeItem(TOKEN_KEY);(remember?localStorage:sessionStorage).setItem(TOKEN_KEY,token);await enter(r.user)}catch(e){showGate("ورود انجام نشد",e.message)}finally{$("#loginBtn").disabled=false}};
$("#loginPassword").onkeydown=e=>{if(e.key==="Enter")$("#loginBtn").click()};
$("#logout").onclick=logout;$("#amount").addEventListener("input",e=>e.target.value=formatMoneyInput(e.target.value));$("#add").onclick=()=>openModal();$("#close").onclick=()=>$("#modal").close();$$(".quick").forEach(b=>b.onclick=()=>openModal(null,b.dataset.kind));$("#save").onclick=saveTransaction;
$("#addMember").onclick=()=>openMember();$("#closeMember").onclick=()=>$("#memberModal").close();$("#saveMember").onclick=saveMember;$("#searchTx").oninput=renderTransactions;$("#monthFilter").onchange=renderTransactions;$("#kindFilter").onchange=renderTransactions;
$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.toggle("active",x===b));$$(".view").forEach(x=>x.classList.toggle("active",x.id===b.dataset.view));scrollTo(0,0)});
$("#share").onclick=async()=>{const url=location.origin+location.pathname;try{await navigator.clipboard.writeText(url);toast("لینک ثابت برنامه کپی شد")}catch{prompt("لینک برنامه",url)}};
$("#updateApp").onclick=async()=>{try{await loadAll();toast("برنامه بروزرسانی شد")}catch(e){toast(e.message)}};
(async()=>{if(!token)return logout();try{await enter(await api("/me"))}catch{logout()}})();

